--ALTER FUNCTION DataIndicada(@Datada VARCHAR(7))
--RETURNS TABLE
--AS
--RETURN
--(
--    SELECT
--        NF.CPF,
--		TC.NOME,
--		TC.VOLUME_DE_COMPRA,
--		CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS "Data Fim",
--        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL,
--		CASE WHEN SUM(INF.QUANTIDADE) < TC.VOLUME_DE_COMPRA THEN 'VENDAS VÁLIDAS'
--ELSE 'VENDAS INVÁLIDAS' END AS "RESULTADO"
--    FROM NOTAS_FISCAIS NF
--    LEFT JOIN ITENS_NOTAS_FISCAIS INF
--        ON NF.NUMERO = INF.NUMERO
--	LEFT JOIN TABELA_DE_CLIENTES TC
--		ON NF.CPF = TC.CPF
--    WHERE NF.DATA_VENDA LIKE CONCAT(@Datada, '%')
--    GROUP BY NF.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
--);

--SELECT * FROM dbo.DataIndicada('2015-01') ORDER BY CPF ASC;



ALTER FUNCTION VENDAANOSUCO(@AnoVenda Varchar(4))

RETURNS TABLE

AS RETURN

(

SELECT
  
	TDP.SABOR,
	CONVERT(VARCHAR(4), NF.DATA_VENDA, 120) AS "Data Fim",
	SUM(INF.QUANTIDADE) AS 'VENDA_ANO',

	ROUND(((CONVERT(FLOAT, SUM(INF.QUANTIDADE)) / (SELECT  SUM(QUANTIDADE) 
	 FROM  ITENS_NOTAS_FISCAIS INF INNER JOIN NOTAS_FISCAIS NF
	 ON INF.NUMERO = NF.NUMERO WHERE NF.DATA_VENDA LIKE '2015' + '%'))*100), 2) as 'PORCENTAGEM'


	 FROM ITENS_NOTAS_FISCAIS INF
	 LEFT JOIN TABELA_DE_PRODUTOS TDP
	 ON INF.CODIGO_DO_PRODUTO = TDP.CODIGO_DO_PRODUTO
	 INNER JOIN NOTAS_FISCAIS NF
	 ON INF.NUMERO = NF.NUMERO
	 WHERE NF.DATA_VENDA LIKE @AnoVenda + '%'
	 GROUP BY TDP.SABOR, CONVERT(VARCHAR(4), NF.DATA_VENDA, 120)
	 
 );
 

SELECT * FROM VENDAANOSUCO('2016') ORDER BY VENDA_ANO DESC;
